<?php
// $Id$
/**
 * @file fail.module
 * Designed to create failures we can debug.
 */


//function fail_init() {
//  if (arg(0) == 'node') {
//    drupal_set_message('this is a test of an argument %argument', array('%argument' => 'no contest'));
//  }
//  watchdog('Tell somebody it is broken', array('%broken' => 'broken'), 'This is not working %arg', 'should be the arg');
//}

function fail_cron() {
//  $x = 1/0;
exit();
}
